# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.exact_search <- function(vec, patterns, max_error = 1L, verbose = TRUE) {
    .Call('_tcR_exact_search', PACKAGE = 'tcR', vec, patterns, max_error, verbose)
}

.exact_search_list <- function(vec, patterns_list, max_error = 1L, verbose = TRUE) {
    .Call('_tcR_exact_search_list', PACKAGE = 'tcR', vec, patterns_list, max_error, verbose)
}

.hamming_search <- function(vec, patterns, max_error = 1L, verbose = TRUE) {
    .Call('_tcR_hamming_search', PACKAGE = 'tcR', vec, patterns, max_error, verbose)
}

.levenshtein_search <- function(vec, patterns, max_error = 1L, verbose = TRUE) {
    .Call('_tcR_levenshtein_search', PACKAGE = 'tcR', vec, patterns, max_error, verbose)
}

